font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size 12

cursor #f5e0dc

# padding
window_padding_width 10

# disable bell
enable_audio_bell no

# disable ligatures if you want
disable_ligatures never

# Smooth scrolling
scrollback_lines 5000

# generated via wallust
include ~/.config/kitty/colors-kitty.conf

background_opacity 0.6

shell zsh
